# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-21 16:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='order',
            new_name='my_order',
        ),
        migrations.RenameField(
            model_name='orderproduct',
            old_name='product',
            new_name='my_product',
        ),
    ]
